//----------------------------------------------------------------------------
// MM_FONT.HPP
//----------------------------------------------------------------------------
// Costanti di traduzione da servizi a simboletti dei fonts "standard"

// Classifiche: Sono dinamiche. Le uniche rimaste sono : 
#define N_N               '\xc0'     //  Alt-192
#define URBANO            '\xff'     //  Alt-255
// NB: I caratteri da 192 a 255 sono riservati per le classifiche

// Simboli generali
#define NOSERVBASE        '\xbc'     //  Alt-188
#define CLDISUNIFORME     '\xAD'     //  Alt-173  
// Servizi
#define AUTO              '\x8f'     //  Alt-143
#define RISTORANTE        '\x91'     //  Alt-145
#define SELFSERVICE       '\x92'     //  Alt-146
#define INVALIDI          '\x93'     //  Alt-147
#define BICI              '\x9d'     //  Alt-157
#define POSTI1A           '\x9f'     //  Alt-159
#define POSTI2A           '\xa0'     //  Alt-160
#define POSTI12A          '\xa1'     //  Alt-161
#define SUPPLEMENTO_IC    '\xa2'     //  Alt-162
#define SUPPLEMENTO_ES    '\xa4'     //  Alt-164
#define PRENOBBLIGITA     '\xa9'     //  Alt-169
#define PRENOTABILE       '\xaa'     //  Alt-170
#define TRENO_VERDE       '\xb0'     //  Alt-176
#define RISTORO           '\xb1'     //  Alt-177
#define RISTOBAR          '\xb2'     //  Alt-178    Sostituisce il  BuffetBar
#define CUCC2A            '\xb3'     //  Alt-179
#define LETTI1A           '\xb4'     //  Alt-180
#define LETTI2A           '\xb5'     //  Alt-181
#define LETTI12A          '\xb6'     //  Alt-182
#define FUMATORI          '\xb8'     //  Alt-184
#define NOFUMATORI        '\xb9'     //  Alt-185
#define ANIMALI           '\x90'     //  Alt-144

// Montagna: Caratteri di periodicit… e simili
#define PP_LAVNOSAB       '\x9a'     //  Alt-154   Periodicit…: lavorativi escluso il sabato
#define PP_NOSAB          '\x9b'     //  Alt-155   Periodicit…: Tutti i giorni escluso il sabato
#define PP_SABFESTIVI     '\x83'     //  Alt-131   Periodicit…: Sabato e festivi
#define PP_COMPLEX        '\xa3'     //  Alt-163   Servizio periodicit… complessa
#define PP_FERIALI        '\xa5'     //  Alt-165   Periodicit…: giorni feriali
#define PP_FESTIVI        '\x84'     //  Alt-132   Periodicit…: giorni festivi
 
// Questi dovrebbero essere obsoleti o non usati
// #define DISUNIFORMEINI    
// #define DISUNIFORMEFIN    
// #define SS_SUPPLEM        
// #define CUCC1A            
// #define SLEEP1A           
// #define SLEEP2A           
// #define BUFFETBAR         // Sostituito dal RISTOBAR

