// Paths fisici da utilizzare per la preparazione dei dati

// Questa variabile di ambiente accetta in input il vecchio formato dei files T
//#define OLD_T_FORMAT

// EMS VA versione aggiornata per install. Win95
#define PATH_IN        "\\EMS\\FILE_T\\BASE\\"
#define PATH_OUT       "\\EMS\\FILE_T\\OUT\\"       // Altro orario
#define PATH_IN2       "\\EMS\\FILE_T2\\BASE\\"     // Altro orario
#define PATH_OUT2      "\\EMS\\FILE_T2\\OUT\\"
#define PATH_DATI      "\\EMS\\DATIMOT\\"
#define PATH_DUMMY     "\\EMS\\MDUMMY\\"       // Files che possono essere buttati
#define PATH_TEMP      "\\EMS\\MTEMP\\"     // Files di lavoro da cancellare immediatamente
#define PATH_POLIM     "\\EMS\\POLIMET\\"
#define PATH_INTERMED  "\\EMS\\INTEGRAZ\\SUBSYS\\MOTORE\\INTERMED\\"
#define PATH_CVB       "\\EMS\\CVB_UFF\\"

// Numero di righe per pagina nei DUMP
#define NUMRIGHE_DUMP 25
