void initabls()
{
    NomiServizi += "HaNoteGeneriche"      ;
    NomiServizi += "HaNoteDiVendita"      ;
    NomiServizi += "PrenotDisUniforme"    ;
    NomiServizi += "Prenotabilita"        ;
    NomiServizi += "PrenObbligItalia"     ;
    NomiServizi += "PrenObbligEstero"     ;
    NomiServizi += "PrenotabileSolo1Cl"   ;
    NomiServizi += "ServTraspDisUniformi" ;
    NomiServizi += "ServizioBase"         ;
    NomiServizi += "PostiASederePrima"    ;
    NomiServizi += "PostiASedereSeconda"  ;
    NomiServizi += "SleeperettePrima"     ;
    NomiServizi += "SleeperetteSeconda"   ;
    NomiServizi += "CuccettePrima"        ;
    NomiServizi += "CuccetteSeconda"      ;
    NomiServizi += "VagoniLettoPrima"     ;
    NomiServizi += "VagoniLettoSeconda"   ;
    NomiServizi += "AutoAlSeguito"        ;
    NomiServizi += "Invalidi"             ;
    NomiServizi += "Biciclette"           ;
    NomiServizi += "Animali"              ;
    NomiServizi += "ServGenerDisUniformi" ;
    NomiServizi += "Ristoro"              ;
    NomiServizi += "BuffetBar"            ;
    NomiServizi += "SelfService"          ;
    NomiServizi += "Ristorante"           ;
    NomiServizi += "Fumatori"             ;
    NomiServizi += "ClassificaDisUniforme";
    NomiServizi += "#"                    ;
    NomiServizi += "#"                    ;
    NomiServizi += "#"                    ;
    NomiServizi += "#"                    ;


   sprintf(arrayNomiServizi[0],"HaNoteGeneriche");
   sprintf(arrayNomiServizi[1],"HaNoteDiVendita");
   sprintf(arrayNomiServizi[2],"PrenotDisUniforme");
   sprintf(arrayNomiServizi[3],"Prenotabilita");
   sprintf(arrayNomiServizi[4],"PrenObbligItalia");
   sprintf(arrayNomiServizi[5],"PrenObbligEstero");
   sprintf(arrayNomiServizi[6],"PrenotabileSolo1Cl");
   sprintf(arrayNomiServizi[7],"ServTraspDisUniformi");
   sprintf(arrayNomiServizi[8],"ServizioBase");
   sprintf(arrayNomiServizi[9],"PostiASederePrima");
   sprintf(arrayNomiServizi[10],"PostiASedereSeconda");
   sprintf(arrayNomiServizi[11],"SleeperettePrima");
   sprintf(arrayNomiServizi[12],"SleeperetteSeconda");
   sprintf(arrayNomiServizi[13],"CuccettePrima");
   sprintf(arrayNomiServizi[14],"CuccetteSeconda");
   sprintf(arrayNomiServizi[15],"VagoniLettoPrima");
   sprintf(arrayNomiServizi[16],"VagoniLettoSeconda");
   sprintf(arrayNomiServizi[17],"AutoAlSeguito");
   sprintf(arrayNomiServizi[18],"Invalidi");
   sprintf(arrayNomiServizi[19],"Biciclette");
   sprintf(arrayNomiServizi[20],"Animali");
   sprintf(arrayNomiServizi[21],"ServGenerDisUniformi");
   sprintf(arrayNomiServizi[22],"Ristoro");
   sprintf(arrayNomiServizi[23],"BuffetBar");
   sprintf(arrayNomiServizi[24],"SelfService");
   sprintf(arrayNomiServizi[25],"Ristorante");
   sprintf(arrayNomiServizi[26],"Fumatori");
   sprintf(arrayNomiServizi[27],"ClassificaDisUniforme");


   sprintf(arrayAcrServizi[0],"NGen");
   sprintf(arrayAcrServizi[1],"NVen");
   sprintf(arrayAcrServizi[2],"PrDU");
   sprintf(arrayAcrServizi[3],"Pr");
   sprintf(arrayAcrServizi[4],"PrO");
   sprintf(arrayAcrServizi[5],"PrOE");
   sprintf(arrayAcrServizi[6],"Pr1C");
   sprintf(arrayAcrServizi[7],"STDU");
   sprintf(arrayAcrServizi[8],"SB");
   sprintf(arrayAcrServizi[9],"1A");
   sprintf(arrayAcrServizi[10],"2A");
   sprintf(arrayAcrServizi[11],"S11A");
   sprintf(arrayAcrServizi[12],"S12A");
   sprintf(arrayAcrServizi[13],"Cu1A");
   sprintf(arrayAcrServizi[14],"Cu2A");
   sprintf(arrayAcrServizi[15],"VL1A");
   sprintf(arrayAcrServizi[16],"VL2A");
   sprintf(arrayAcrServizi[17],"AutS");
   sprintf(arrayAcrServizi[18],"H");
   sprintf(arrayAcrServizi[19],"Bic");
   sprintf(arrayAcrServizi[20],"Anim");
   sprintf(arrayAcrServizi[21],"SGDU");
   sprintf(arrayAcrServizi[22],"MB");
   sprintf(arrayAcrServizi[23],"BBar");
   sprintf(arrayAcrServizi[24],"SS");
   sprintf(arrayAcrServizi[25],"Rist");
   sprintf(arrayAcrServizi[26],"Fum");
   sprintf(arrayAcrServizi[27],"ClDU");


   sprintf(arrayGifServizi[0],"#");
   sprintf(arrayGifServizi[1],"#");
   sprintf(arrayGifServizi[2],"#");
   sprintf(arrayGifServizi[3],"#");
   sprintf(arrayGifServizi[4],"%sPRENOTOB.GIF",PATH_IMG);
   sprintf(arrayGifServizi[5],"%sPRENOTOB.GIF",PATH_IMG);
   sprintf(arrayGifServizi[6],"#");
   sprintf(arrayGifServizi[7],"#");
   sprintf(arrayGifServizi[8],"#");
   sprintf(arrayGifServizi[9],"%s1A.GIF",PATH_IMG);
   sprintf(arrayGifServizi[10],"%s2A.GIF",PATH_IMG);
   sprintf(arrayGifServizi[11],"#");
   sprintf(arrayGifServizi[12],"#");
   sprintf(arrayGifServizi[13],"%scucc1.gif",PATH_IMG);
   sprintf(arrayGifServizi[14],"%scucc2.gif",PATH_IMG);
   sprintf(arrayGifServizi[15],"%sletti1.gif",PATH_IMG);
   sprintf(arrayGifServizi[16],"%sletti2.gif",PATH_IMG);
   sprintf(arrayGifServizi[17],"%sautos.gif",PATH_IMG);
   sprintf(arrayGifServizi[18],"%shandicap.gif",PATH_IMG);
   sprintf(arrayGifServizi[19],"%sbici.gif",PATH_IMG);
   sprintf(arrayGifServizi[20],"%sanimali.gif",PATH_IMG);
   sprintf(arrayGifServizi[21],"#");
   sprintf(arrayGifServizi[22],"%sminibar.gif",PATH_IMG);
   sprintf(arrayGifServizi[23],"#");
   sprintf(arrayGifServizi[24],"%sselfserv.gif",PATH_IMG);
   sprintf(arrayGifServizi[25],"%sristor.gif",PATH_IMG);
   sprintf(arrayGifServizi[26],"%sfumat.gif",PATH_IMG);
   sprintf(arrayGifServizi[27],"#");



   sprintf(arrayDescServizi[0],"HaNoteGeneriche");
   sprintf(arrayDescServizi[1],"HaNoteDiVendita");
   sprintf(arrayDescServizi[2],"PrenotDisUniforme");
   sprintf(arrayDescServizi[3],"Prenotazione facoltativa a pagamento");
   sprintf(arrayDescServizi[4],"Prenotazione obbligatoria");
   sprintf(arrayDescServizi[5],"Prenotazione obbigatoria all'estero");
   sprintf(arrayDescServizi[6],"Prenotabile solo in 1&#170; classe");
   sprintf(arrayDescServizi[7],"ServTraspDisUniformi");
   sprintf(arrayDescServizi[8],"Servizio Base");
   sprintf(arrayDescServizi[9],"Servizio di 1&#170; classe");
   sprintf(arrayDescServizi[10],"Servizio di 2&#170; classe");
   sprintf(arrayDescServizi[11],"Sleeperette di 1&#170; classe");
   sprintf(arrayDescServizi[12],"Sleeperette di 2&#170; classe");
   sprintf(arrayDescServizi[13],"Treno con cuccette di 1&#170; classe");
   sprintf(arrayDescServizi[14],"Treno con cuccette di 2&#170; classe");
   sprintf(arrayDescServizi[15],"Treno con carrozze letto di 1&#170; classe");
   sprintf(arrayDescServizi[16],"Treno con carrozze letto di 2&#170; classe");
   sprintf(arrayDescServizi[17],"Carro auto a seguito");
   sprintf(arrayDescServizi[18],"Treno con servizio di trasporto di invalidi su sedie a rotelle");
   sprintf(arrayDescServizi[19],"Treno con servizio di trasporto biciclette");
   sprintf(arrayDescServizi[20],"Trasporto di piccoli animali");
   sprintf(arrayDescServizi[21],"ServGenerDisUniformi");
   sprintf(arrayDescServizi[22],"Treno con servizio di ristoro o minibar");
   sprintf(arrayDescServizi[23],"BuffetBar");
   sprintf(arrayDescServizi[24],"Treno con carrozza self-service");
   sprintf(arrayDescServizi[25],"Treno con carrozza ristorante");
   sprintf(arrayDescServizi[26],"Treno con aree fumatori");
   sprintf(arrayDescServizi[27],"ClassificaDisUniforme");

   sprintf(arrayTipiTreni[0],"Pendolino");
   sprintf(arrayTipiTreni[1],"Intercity");
   sprintf(arrayTipiTreni[2],"Espresso");
   sprintf(arrayTipiTreni[3],"Diretto");
   sprintf(arrayTipiTreni[4],"Interregionale");
   sprintf(arrayTipiTreni[5],"Regionale");
   sprintf(arrayTipiTreni[6],"Locale");
   sprintf(arrayTipiTreni[7],"Accelerato");
   sprintf(arrayTipiTreni[8],"Direttissimo");
   sprintf(arrayTipiTreni[9],"Eurocity");
   sprintf(arrayTipiTreni[10],"Euronight");
   sprintf(arrayTipiTreni[11],"ETR470");
   sprintf(arrayTipiTreni[12],"ETR500");
   sprintf(arrayTipiTreni[13],"Eurostar");
   sprintf(arrayTipiTreni[14],"Traghetto");
   sprintf(arrayTipiTreni[15],"Metropolitano");
   sprintf(arrayTipiTreni[16],"Autobus");
   sprintf(arrayTipiTreni[17],"NON NOTO");
   sprintf(arrayTipiTreni[18],"Collegamento Urbano");
   sprintf(arrayTipiTreni[19],"TGV");

   sprintf(arrayAcrTreni[0],"P");
   sprintf(arrayAcrTreni[1],"IC");
   sprintf(arrayAcrTreni[2],"E");
   sprintf(arrayAcrTreni[3],"D");
   sprintf(arrayAcrTreni[4],"IR");
   sprintf(arrayAcrTreni[5],"R");
   sprintf(arrayAcrTreni[6],"LC");
   sprintf(arrayAcrTreni[7],"AC");
   sprintf(arrayAcrTreni[8],"DDC");
   sprintf(arrayAcrTreni[9],"EC");
   sprintf(arrayAcrTreni[10],"EN");
   sprintf(arrayAcrTreni[11],"CIS");
   sprintf(arrayAcrTreni[12],"500");
   sprintf(arrayAcrTreni[13],"ES");
   sprintf(arrayAcrTreni[14],"TRG");
   sprintf(arrayAcrTreni[15],"M");
   sprintf(arrayAcrTreni[16],"BUS");
   sprintf(arrayAcrTreni[17],"NN");
   sprintf(arrayAcrTreni[18],"TU");
   sprintf(arrayAcrTreni[19],"TGV");

   sprintf(arrayGifTreni[0],"%scla_p.gif",PATH_IMG);
   sprintf(arrayGifTreni[1],"%scla_ic.gif",PATH_IMG);
   sprintf(arrayGifTreni[2],"%scla_e.gif",PATH_IMG);
   sprintf(arrayGifTreni[3],"%scla_d.gif",PATH_IMG);
   sprintf(arrayGifTreni[4],"%scla_ir.gif",PATH_IMG);
   sprintf(arrayGifTreni[5],"%scla_r.gif",PATH_IMG);
   sprintf(arrayGifTreni[6],"%scla_lc.gif",PATH_IMG);
   sprintf(arrayGifTreni[7],"%scla_ac.gif",PATH_IMG);
   sprintf(arrayGifTreni[8],"%scla_ddc.gif",PATH_IMG);
   sprintf(arrayGifTreni[9],"%scla_ec.gif",PATH_IMG);
   sprintf(arrayGifTreni[10],"%scla_en.gif",PATH_IMG);
   sprintf(arrayGifTreni[11],"%scla_cis.gif",PATH_IMG);
   sprintf(arrayGifTreni[12],"%scla_500.gif",PATH_IMG);
   sprintf(arrayGifTreni[13],"%scla_es.gif",PATH_IMG);
   sprintf(arrayGifTreni[14],"%scla_trg.gif",PATH_IMG);
   sprintf(arrayGifTreni[15],"%scla_m.gif",PATH_IMG);
   sprintf(arrayGifTreni[16],"%scla_bus.gif",PATH_IMG);
   sprintf(arrayGifTreni[17],"%scla_nn.gif",PATH_IMG);
   sprintf(arrayGifTreni[18],"%scla_tu.gif",PATH_IMG);
   sprintf(arrayGifTreni[19],"%scla_tgv.gif",PATH_IMG);

   sprintf(arrayDescTreni[0],"Treno Pendolino ETR450-ETR460. Non sono ammessi viaggiatori in piedi");
   sprintf(arrayDescTreni[1],"Intercity - Treni di qualit&agrave; in servizio interno");
   sprintf(arrayDescTreni[2],"Treno espresso");
   sprintf(arrayDescTreni[3],"Treno diretto");
   sprintf(arrayDescTreni[4],"Treno interregionale");
   sprintf(arrayDescTreni[5],"Treno regionale");
   sprintf(arrayDescTreni[6],"Treno locale delle ferrovie concesse");
   sprintf(arrayDescTreni[7],"Treno accelerato delle ferrovie concesse");
   sprintf(arrayDescTreni[8],"Treno direttissimo delle ferrovie concesse");
   sprintf(arrayDescTreni[9],"Eurocity - Treni di qualit&agrave; in servizio internazionale diurno");
   sprintf(arrayDescTreni[10],"Euronight - Treni di qualit&agrave; in servizio internazionale notturno");
   sprintf(arrayDescTreni[11],"Treno ETR470 Pendolino della societ&agrave; Cisalpino. Non sono ammessi viaggiatori in piedi");
   sprintf(arrayDescTreni[12],"Treno ETR500. Non sono ammessi viaggiatori in piedi");
   sprintf(arrayDescTreni[13],"Treno Eurostar. Il treno percorre l'Eurotunnel");
   sprintf(arrayDescTreni[14],"Servizi lacuali o marittimi");
   sprintf(arrayDescTreni[15],"Treno in servizio metropolitano");
   sprintf(arrayDescTreni[16],"Servizio automobilistico sostitutivo con fermata sul piazzale esterno della stazione FS");
   sprintf(arrayDescTreni[17],"Non noto");
   sprintf(arrayDescTreni[18],"Autobus, metropolitana, stazioni vicine o altro tipo di trasporto urbano non FS");
   sprintf(arrayDescTreni[19],"TGV");

}                                                           /* end function*/
